### ISSUE TITLE
Does not support using a single value instead of list for Transform

### ISSUE THREAD

**Issue by SimonCMoore** [cdklabs/cdk-from-cfn#365]
CDK migrate does not support using a single value instead of list in at least this case (maybe others? not checked).

In a template where the transform value is specified as a single value rather than list which is common in examples/docs e.g. https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy.html)
i.e. this line
```
Transform: AWS::Serverless-2016-10-31
```
Results in this Error when using CDK migrate
```
This is an experimental feature. We make no guarantees about the outcome or stability of the functionality.
 ❌  Migrate failed for testcdkmigrate: stack generation failed due to error 'Transform: invalid type: string "AWS::Serverless-2016-10-31", expected a sequence at line 1 column 12'
```
Changing the template to use a list instead works as a workaround
```
Transform: 
  - AWS::Serverless-2016-10-31
```
Expectations are both formats work.

**Comment by TheRealAmazonKendra** [comment]
I don't believe we support transforms at this time as SAM templates weren't in the original scope of this project.
