### ISSUE TITLE
Recommend adding license headers to source files

### ISSUE THREAD

**Issue by hyandell** [cdklabs/cdk-from-cfn#466]
Having license headers on files is a best practice, providing clarity when those files are disconnected from the top level LICENSE file. 

For this project I believe the default license header would be:

    // Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
    // SPDX-License-Identifier: Apache-2.0 OR MIT

**Comment by iph** [comment]
I'm new to this part of OSS. 

If the files don't diverge from the top level license, why would we need the header?

**Comment by hyandell** [comment]
A couple.

First - files don't stay within packages/repositories. They travel around getting copied and licensing easily gets confusing if it's not clear. Thinking more recent - this includes automation like ML data sets that are going to better understand metadata in the file than somewhere near the file.

Second - it creates the right foundation when other open source is incorporated into the file (rather than having the other contents licensing confusingly seem to subsume the original content), and it educates developers to be aware of licensing as a constant background rather than something they only think of once 10 years ago.

**Comment by iph** [comment]
Thanks for the deets! 

Added all except for the `tests/` for now just because there are "quite a few files" in there.

**Comment by hyandell** [comment]
Does that PR relate?  The Files Changed tab doesn't seem to match to licensing.

**Comment by iph** [comment]
One day, I will learn to use github correctly 😂

Updated the branch + PR with the actual commit I made yesterday.

**Comment by hyandell** [comment]
Thank you :)
